colorScheme = "congo"
defaultAppearance = "light"
autoSwitchAppearance = true

[header]
layout = "basic"

[footer]
showCopyright = true
showThemeAttribution = true

[homepage]
layout = "profile"
showRecent = true
showRecentItems = 5

[article]
showDate = true
showAuthor = true
showReadingTime = true
showTableOfContents = true
showRelatedContent = false
